### ISSUE TITLE
Uncaught Error: Undefined constant "uncounted"

### ISSUE THREAD

**Issue by speedytom** [rpi-dotcio/phpLicenseWatcher#144]
**Describe the bug**
#0 /var/www/html/phpLicenseWatcher/details.php(28): list_licenses_in_use()
#1 {main}
  thrown in /var/www/html/phpLicenseWatcher/details.php on line 196" while reading response header from upstream, client: 10.10.40.38, server: _, request: "GET /licenses/details.php?listing=0&server=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "10.10.0.245", referrer: "http://10.10.0.245/licenses/index.php"
2024/04/09 14:55:03 [error] 73549#73549: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "uncounted" in /var/www/html/phpLicenseWatcher/details.php:196
Stack trace:
#0 /var/www/html/phpLicenseWatcher/details.php(28): list_licenses_in_use()
#1 {main}
  thrown in /var/www/html/phpLicenseWatcher/details.php on line 196" while reading response header from upstream, client: 10.10.40.38, server: _, request: "GET /licenses/details.php?listing=0&server=2 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "10.10.0.245", referrer: "http://10.10.0.245/licenses/index.php"

**Comment by speedytom** [comment]
[0001-fixed-Uncaught-Error-Undefined-constant-uncounted.patch.txt](https://github.com/rpi-dotcio/phpLicenseWatcher/files/14919080/0001-fixed-Uncaught-Error-Undefined-constant-uncounted.patch.txt)

Fixed issue.

**Comment by pbailie** [comment]
I have confirmed that this issue exists in PHP 8.1 and 8.2.  PHP 7.4 doesn't throw this exception.

Thank you for reporting it.
